#ifndef CALCULATE_PHONEMES_PROBABILITIES_TEST_H
#define CALCULATE_PHONEMES_PROBABILITIES_TEST_H

int prepare_for_testing_of_calculate_phonemes_probabilities();
int init_suite_calculate_phonemes_probabilities();
int clean_suite_calculate_phonemes_probabilities();
void calculate_phonemes_probabilities_valid_test_1();
void calculate_phonemes_probabilities_invalid_test_1();

#endif // CALCULATE_PHONEMES_PROBABILITIES_TEST_H
