#ifndef CREATE_WORDS_VOCABULARY_TREE_TEST_H
#define CREATE_WORDS_VOCABULARY_TREE_TEST_H

int prepare_for_testing_of_create_words_vocabulary_tree();
int init_suite_create_words_vocabulary_tree();
int clean_suite_create_words_vocabulary_tree();
void create_words_vocabulary_tree_valid_test_1();
void create_words_vocabulary_tree_valid_test_2();
void create_words_vocabulary_tree_invalid_test_1();

#endif // CREATE_WORDS_VOCABULARY_TREE_TEST_H
